apiVersion: v1
kind: Service
metadata:
    name: jenkins-service
    namespace: build
spec:
    type: LoadBalancer
    selector:
        app: jenkins
    ports:
        - port: 8080
          name: jenkins
          targetPort: 8080
        - port: 50000
          name: jenkins2
          targetPort: 50000