apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: build
    name: simple-app
    labels:
        app: simple-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: simple-app
    template:
        metadata:
            labels:
                app: simple-app
        spec:
            containers:
            -   name: simple-app
                image: aarondownward/maven-app:latest
                imagePullPolicy: Always
            restartPolicy: Always
